name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Adjust for your Blazor version

      - name: Install .NET Workloads
        run: dotnet workload install wasm-tools

      - name: Build Blazor WASM in Release Mode
        run: dotnet publish ./BlazorWasm9 -c Release --output release

      - name: Compress DLL & WASM files with Brotli
        run: |
          sudo apt-get install brotli
          brotli -Z -f release/wwwroot/_f
